name: Pipeline action

on:
  push:
    branches:
    - master
    - develop
  workflow_dispatch:
  repository_dispatch:
    types: [parent_changed]
    
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out CODE
      uses: actions/checkout@v2
    
    - name: Set branch after repo dispatch
      if: github.event_name == 'repository_dispatch'
      run: |
        echo "BRANCH=develop" >> $GITHUB_ENV

    - name: Set branch env for other triggers
      if: github.event_name != 'repository_dispatch'
      run: |
        echo "BRANCH=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

    - name: Set other build variables
      id: version
      run : |
        echo "GITHUB_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
        echo SUITECRM_VERSION=$(curl -s -o -  https://raw.githubusercontent.com/salesagility/SuiteCRM/master/suitecrm_version.php | grep suitecrm_version | sed "s|$suitecrm_version.*'\(.*\)';|\1|") >> $GITHUB_ENV
    - name: Set build version
      run: |
        echo "BUILD_VERSION=$BRANCH-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV
    
    - name: Build master base image and push it to Registry
      if: env.BRANCH == 'master'
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: suitecrm7/suitecrm7
        # Tags override for Docker image
        tags: base, base-latest, base-${{ env.BRANCH }}-latest, base-${{ env.BRANCH }}, base-${{ env.BUILD_VERSION }}, base-${{ env.GITHUB_HASH }}  # optional
        # Target Docker registry
        registry: ${{ secrets.REGISTRY_URL }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Docker build target passed via --target
        target: base-final # optional
        # Docker registry username
        username:  ${{ secrets.REGISTRY_USER }}  # optional
        # Docker registry password
        password: ${{ secrets.REGISTRY_PASSWORD }} # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: false # optional, default is false
        
    - name: Build non-master base image and push it to Registry
      if: env.BRANCH != 'master'
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: suitecrm7/suitecrm7
        # Tags override for Docker image
        tags: base-${{ env.BRANCH }}-latest, base-${{ env.BRANCH }}, base-${{ env.BUILD_VERSION }}, base-${{ env.GITHUB_HASH }}  # optional
        # Target Docker registry
        registry: ${{ secrets.REGISTRY_URL }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Docker build target passed via --target
        target: base-final # optional
        # Docker registry username
        username:  ${{ secrets.REGISTRY_USER }}  # optional
        # Docker registry password
        password: ${{ secrets.REGISTRY_PASSWORD }} # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: false # optional, default is false
          
    - name: Build master fpm image and push it to Registry
      if: env.BRANCH == 'master'
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: suitecrm7/suitecrm7
        # Tags override for Docker image
        tags: fpm, fpm-latest, fpm-${{ env.BRANCH }}-latest, fpm-${{ env.BRANCH }}, fpm-${{ env.BUILD_VERSION }}, fpm-${{ env.GITHUB_HASH }}  # optional
        # Target Docker registry
        registry: ${{ secrets.REGISTRY_URL }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Docker build target passed via --target
        target: serve-php-fpm # optional
        # Docker registry username
        username:  ${{ secrets.REGISTRY_USER }}  # optional
        # Docker registry password
        password: ${{ secrets.REGISTRY_PASSWORD }} # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: false # optional, default is false

    - name: Build non-master fpm image and push it to Registry
      if: env.BRANCH != 'master'
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: suitecrm7/suitecrm7
        # Tags override for Docker image
        tags: fpm-${{ env.BRANCH }}-latest, fpm-${{ env.BRANCH }}, fpm-${{ env.BUILD_VERSION }}, fpm-${{ env.GITHUB_HASH }}  # optional
        # Target Docker registry
        registry: ${{ secrets.REGISTRY_URL }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Docker build target passed via --target
        target: serve-php-fpm # optional
        # Docker registry username
        username:  ${{ secrets.REGISTRY_USER }}  # optional
        # Docker registry password
        password: ${{ secrets.REGISTRY_PASSWORD }} # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: false # optional, default is false

    - name: Build master apache2 image and push it to Registry
      if: env.BRANCH == 'master'
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: suitecrm7/suitecrm7
        # Tags override for Docker image
        tags: latest, apache2, apache2-latest, apache2-${{ env.BRANCH }}-latest, apache2-${{ env.BRANCH }}, apache2-${{ env.BUILD_VERSION }}, apache2-${{ env.GITHUB_HASH }}  # optional
        # Target Docker registry
        registry: ${{ secrets.REGISTRY_URL }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Docker build target passed via --target
        target: serve-php-apache2 # optional
        # Docker registry username
        username:  ${{ secrets.REGISTRY_USER }}  # optional
        # Docker registry password
        password: ${{ secrets.REGISTRY_PASSWORD }} # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: true # optional, default is false
        
    - name: Build non-master apache2 image and push it to Registry
      if: env.BRANCH != 'master'
      # You may pin to the exact commit or the version.
      # uses: mr-smithers-excellent/docker-build-push@a7fe6652db5c7274374844e81692992f5a2befb9
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        # Name of the Docker image
        image: suitecrm7/suitecrm7
        # Tags override for Docker image
        tags: apache2-${{ env.BRANCH }}-latest, apache2-${{ env.BRANCH }}, apache2-${{ env.BUILD_VERSION }}, apache2-${{ env.GITHUB_HASH }}  # optional
        # Target Docker registry
        registry: ${{ secrets.REGISTRY_URL }}
        # Location of Dockerfile, if not Dockerfile in root directory
        dockerfile: Dockerfile # optional, default is Dockerfile
        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Docker build target passed via --target
        target: serve-php-apache2 # optional
        # Docker registry username
        username:  ${{ secrets.REGISTRY_USER }}  # optional
        # Docker registry password
        password: ${{ secrets.REGISTRY_PASSWORD }} # optional
        # Adds latest tag to auto-generated GitOps tag
        addLatest: false # optional, default is false
