name: Build pipeline

on:
  push:
    branches:
    - master
    - develop
  workflow_dispatch:
  repository_dispatch:
    types:
    - build_needed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        target-stage: [ base, fpm, apache2 ]
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE_NAME: suitecrm7/suitecrm7
      REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
      REGISTRY_USER:  ${{ secrets.REGISTRY_USER }} # If needed
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }} # If needed

    steps:
    - name: Code checkout
      uses: actions/checkout@v3

    - name: Prepare for build
      run: |

        # Set build variables
        echo "BRANCH=$(echo ${GITHUB_REF_NAME})" >> $GITHUB_ENV
        echo "GITHUB_HASH=$(git rev-parse --short "$GITHUB_SHA")" >> $GITHUB_ENV
        echo "BUILD_VERSION=$BRANCH-$APP_VERSION-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

    - name: Lint Dockerfile before build
      if: github.event_name == 'push'
      uses: hadolint/hadolint-action@v3.1.0
      with:
        dockerfile: Dockerfile
        failure-threshold: warning

    - name: Build master images and push them to Registry
      if: env.BRANCH == 'master'
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: ${{ env.DOCKER_IMAGE_NAME }}
        tags: latest, ${{ matrix.target-stage }}, ${{ matrix.target-stage }}-latest, ${{ matrix.target-stage }}-${{ env.BRANCH }}-latest, ${{ matrix.target-stage }}-${{ env.BRANCH }}, ${{ matrix.target-stage }}-${{ env.BUILD_VERSION }}, ${{ matrix.target-stage }}-${{ env.GITHUB_HASH }}, ${{ matrix.target-stage }}-${{ env.APP_VERSION }}-${{ env.BRANCH }}, ${{ matrix.target-stage }}-${{ env.APP_VERSION }}  # optional
        registry: ${{ env.REGISTRY_URL }}
        dockerfile: Dockerfile # optional, default is Dockerfile
        target: ${{ matrix.target-stage }} # optional
        username:  ${{ env.REGISTRY_USER }}  # optional
        password: ${{ env.REGISTRY_PASSWORD }} # optional

        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Adds latest tag to auto-generated GitOps tag
        #addLatest: false # optional, default is false

    - name: Build non-master images and push them to Registry
      if: env.BRANCH != 'master'
      uses: mr-smithers-excellent/docker-build-push@v5.6
      with:
        image: ${{ env.DOCKER_IMAGE_NAME }}
        tags: ${{ matrix.target-stage }}-${{ env.BRANCH }}-latest, ${{ matrix.target-stage }}-${{ env.BRANCH }}, ${{ matrix.target-stage }}-${{ env.BUILD_VERSION }}, ${{ matrix.target-stage }}-${{ env.GITHUB_HASH }}, ${{ matrix.target-stage }}-${{ env.APP_VERSION }}-${{ env.BRANCH }} # optional
        registry: ${{ env.REGISTRY_URL }}
        dockerfile: Dockerfile # optional, default is Dockerfile
        target: ${{ matrix.target-stage }} # optional
        username:  ${{ env.REGISTRY_USER }}  # optional
        password: ${{ env.REGISTRY_PASSWORD }} # optional

        # Docker build arguments passed via --build-arg
        #buildArgs: # optional
        # Docker build labels passed via --label
        #labels: # optional
        # Adds latest tag to auto-generated GitOps tag
        #addLatest: false # optional, default is false